CREATE TABLE bodies (
    id int PRIMARY KEY generated by default as identity,
    name VARCHAR ( 50 ) UNIQUE NOT NULL
);

CREATE TABLE weels (
    id int PRIMARY KEY generated by default as identity,
    name VARCHAR ( 50 ) UNIQUE NOT NULL
);

CREATE TABLE cars (
       id int PRIMARY KEY generated by default as identity,
       body_id int references bodies(id),
       weel_id int references weels(id),
       name VARCHAR ( 150 ) NOT NULL,
       num_of_weel int
);


INSERT INTO bodies(name) VALUES ('sedan');
INSERT INTO bodies(name) VALUES ('hatchback');

INSERT INTO weels(name) VALUES ('R16');
INSERT INTO weels(name) VALUES ('R15');
INSERT INTO weels(name) VALUES ('R17');

INSERT INTO cars (body_id, weel_id, name, num_of_weel) VALUES (1,2, 'Жигули', 4);
INSERT INTO cars (body_id, weel_id, name, num_of_weel) VALUES (2,2, 'Mersedes', 6);
